// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @constructor
 */
export namespace RPC {
    export class ErrorResponse {
        bb: flatbuffers.ByteBuffer | null = null;

        bb_pos: number = 0;
        /**
         * @param number i
         * @param flatbuffers.ByteBuffer bb
         * @returns ErrorResponse
         */
        __init(i: number, bb: flatbuffers.ByteBuffer): ErrorResponse {
            this.bb_pos = i;
            this.bb = bb;
            return this;
        }

        /**
         * @param flatbuffers.ByteBuffer bb
         * @param ErrorResponse= obj
         * @returns ErrorResponse
         */
        static getRoot(
            bb: flatbuffers.ByteBuffer,
            obj?: ErrorResponse
        ): ErrorResponse {
            return (obj || new ErrorResponse()).__init(
                bb.readInt32(bb.position()) + bb.position(),
                bb
            );
        }

        /**
         * @param flatbuffers.ByteBuffer bb
         * @param ErrorResponse= obj
         * @returns ErrorResponse
         */
        static getSizePrefixedRoot(
            bb: flatbuffers.ByteBuffer,
            obj?: ErrorResponse
        ): ErrorResponse {
            bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
            return (obj || new ErrorResponse()).__init(
                bb.readInt32(bb.position()) + bb.position(),
                bb
            );
        }

        /**
         * @param flatbuffers.Encoding= optionalEncoding
         * @returns string|Uint8Array|null
         */
        message(): string | null;
        message(
            optionalEncoding: flatbuffers.Encoding
        ): string | Uint8Array | null;
        message(optionalEncoding?: any): string | Uint8Array | null {
            var offset = this.bb!.__offset(this.bb_pos, 4);
            return offset
                ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
                : null;
        }

        /**
         * @param flatbuffers.Builder builder
         */
        static start(builder: flatbuffers.Builder) {
            builder.startObject(1);
        }

        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset messageOffset
         */
        static addMessage(
            builder: flatbuffers.Builder,
            messageOffset: flatbuffers.Offset
        ) {
            builder.addFieldOffset(0, messageOffset, 0);
        }

        /**
         * @param flatbuffers.Builder builder
         * @returns flatbuffers.Offset
         */
        static end(builder: flatbuffers.Builder): flatbuffers.Offset {
            var offset = builder.endObject();
            return offset;
        }

        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset offset
         */
        static finishBuffer(
            builder: flatbuffers.Builder,
            offset: flatbuffers.Offset
        ) {
            builder.finish(offset);
        }

        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset offset
         */
        static finishSizePrefixedBuffer(
            builder: flatbuffers.Builder,
            offset: flatbuffers.Offset
        ) {
            builder.finish(offset, undefined, true);
        }

        static create(
            builder: flatbuffers.Builder,
            messageOffset: flatbuffers.Offset
        ): flatbuffers.Offset {
            ErrorResponse.start(builder);
            ErrorResponse.addMessage(builder, messageOffset);
            return ErrorResponse.end(builder);
        }
    }
}
